### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to create an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a register form where users can enter a username and password. Submitting will create an account for the user and will store the info in the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 02 06 PM](https://user-images.githubusercontent.com/105886708/200424779-d66cd188-94ef-434e-96cd-57b0363df9d2.png)
![Screen Shot 2022-11-07 at 2 02 43 PM](https://user-images.githubusercontent.com/105886708/200424885-765de1ef-2010-49e5-9109-5bdd5050457d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Import DB Designer sql code to schema.sql.
- [x] Add dummy data to data.sql in order to pre-populate demo user account.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Create a route for a POST request that takes the user's input for username and password and:
  - [x] Makes sure that both values were entered correctly. If not, the user receives an error.
  - [x] If both are valid, use argon2 function to create a hashedPassword and insert the two values into the data base.
  - [x] send a 201 status response back to the client. 

### ⚡ Client Tasks

- [x] Create app-context.js.
- [x] Create a nav bar component with app logo and sign up button.
- [x] Create a form component where users can create an account by inputting a username and password.
- [x] Create a PageContainer function the renders the auth page.
- [x] Create an auth page.
- [x] Add a react element type `h1` with text: "MusicFuze".
- [x] Add a react element type `p` with text: "Create an account to get started".
- [x] Create an app component
- [x] Render the auth page and the page container.
- [x] Style all components.
- [x] Initialize state for username and password property.
- [x] Set up handleChange prototype methods for form inputs.
- [x] Set up handleSubmit prototype method for submit button:
  - [x] This should call a fetch promise to set user inputs into the database and create an account.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
