### ISSUE TITLE
Feature: User can log out

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to log out of their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a logout button that users can press to log out of their account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 48 44 PM](https://user-images.githubusercontent.com/105886708/200431901-7f12b595-0b42-42a6-a56c-20a4484ba96b.png)

![Screen Shot 2022-11-07 at 2 48 57 PM](https://user-images.githubusercontent.com/105886708/200431922-b4281d62-dc9e-46aa-bf53-2dc8b6755c75.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Make sure database is properly updating/functioning as intended.

### ☁️ Server Tasks

- [ ] Make sure the server is properly functioning/responding as intended.

### ⚡ Client Tasks

- [x] Create a sign out button in the navbar.
- [x] Create a handle click function on the sign out button that removes the token from local storage.
- [x] Display a modal that asks whether the users wants to sign out or cancel.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
