### ISSUE TITLE
Feature: 4.2 - User can click an artist and see a list of their albums 

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Make sure the database is function/updating as intended.

### ☁️ Server Tasks

- [ ] Create a new route or update an existing one to pull a list of albums from an artist that the user selects.

### ⚡ Client Tasks

- [ ] Fetch the api to pull a list of albums from an artist that the user selects.
- [ ] Create an artist page component that shows some artist information along with their albums
- [ ] Clicking an album should show a list of songs in that album that users can then add to their library.
- [ ] Make all necessary style changes.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
