### ISSUE TITLE
Feature: User can log in

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to login with their username and password.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a login form where users can enter their username and password. If login information is valid, the user will be logged in and taken to the home screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 07 26 PM](https://user-images.githubusercontent.com/105886708/200425721-e40274b9-cefe-4394-b7ed-bbf1438e9a18.png)

![Screen Shot 2022-11-07 at 2 07 43 PM](https://user-images.githubusercontent.com/105886708/200425760-049a8d10-5121-403c-a342-125d38401326.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Make sure database is properly updating/functioning as intended.

### ☁️ Server Tasks

- [x] Require jsonwebtoken.
- [x] Initialize the TOKEN_SECRET in the .env module.
- [x] Create a POST route that:
  - [x] Checks that user enters both username and password.
  - [x] Select a userId and hashedPassword from the database where the username is equal to the provided username.
  - [x] Makes sure that user exists within the database.
  - [x] If user exists, verify that the password provided matches the hashedPassword in the database.
  - [x] Return a user token.

### ⚡ Client Tasks

- [x] Create a sign-in button on the navbar.
- [x] Create a 'hashChange' event listeners that changes the hash route to either sign-up or sing-in based on which button was pressed:
  - [x] Define a parseRoute function that updates the fragment identifier of the URL.
  - [x] Event listeners should be written in the ComponentDidMount function in the app component.
- [x] Initialize state in the app component that sets the properties of:
  - [x] User to null.
  - [x] Route to `parseRoute(window.location.hash)`.
- [x] Updated the auth page text and form submit button based on which hash route the page is currently on.
- [x] Define a Redirect function that directs which page component should be rendered based on the hash route.
- [x] Create an empty home page that will load after component mount and redirects user to sign in page.
- [x] After page successfully mounts with null, load the auth page with 'sign-in' props in ComponentDidMount.
- [x] Create a handleSignIn prototype method that:
  - [x] Stores the user token in local storage.
  - [x] Updates the user property of state from null to a valid userId and username.
- [x] Create a variation of the handleSubmit function on the auth-form.jsx module:
  - [x] This should specify the target url to 'sign-in'.
  - [x] If hash route is 'sign-up', set it to 'sign-in'.
  - [x] If both user and token exist, onSignIn method with the result of the fetch.
- [x]  Add invalid login error message to client side.
- [x] Successfully render the home page when a user logins in with a valid account.
### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
