### ISSUE TITLE
Feature: User can search up song

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to search up songs by song title, artist name, or album name

## 📐 Functionality

Create a discover page display with a dynamic search bar where users can look up songs. There will be separate tabs for top results, artists, albums, and songs. Click on an artist will take you to the artists discover page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 14 16 PM](https://user-images.githubusercontent.com/105886708/200426884-9f6d0903-9f35-4634-beec-c09e106e7d88.png)

![Screen Shot 2022-11-07 at 2 14 41 PM](https://user-images.githubusercontent.com/105886708/200426914-f0ab1a7e-28c9-4e8b-811c-6846811869d2.png)

![Screen Shot 2022-11-07 at 2 14 53 PM](https://user-images.githubusercontent.com/105886708/200426930-294b2771-062b-491a-b37a-eee1c1e63ee5.png)

![Screen Shot 2022-11-07 at 2 46 56 PM](https://user-images.githubusercontent.com/105886708/200431645-548b5dd6-5888-46c2-abdc-08fc93c91193.png)

![Screen Shot 2022-11-07 at 2 47 07 PM](https://user-images.githubusercontent.com/105886708/200431668-ad7f3911-7aac-4abd-a91c-d6f75ebf8c36.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Make sure database is still functioning as intended.

### ☁️ Server Tasks

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Create a GET route to the deezer api that returns tracks with track info e.g. track name, artist, album, images:
  - [x] User's can do a general search.
  - [x] User's can do a search by artist name.
  - [x] User's can do a search by album name.
  - [x] User's can do a search by song name.

### ⚡ Client Tasks

- [x] Update the nav bar for the home page.
- [x] Create a discover page (this can be empty for now).
- [x] Create a hash routing path that swaps users between to home page and discover page.
- [x] Add components to discover page:
  - [x] Input for search and submit button.
  - [x] Artist section that calls fetch with an artist search.
  - [x] Album section that calls fetch with an album search.
  - [x] Songs section that calls fetch with a song search.
- [x] When user are on the Discover page without a search filter applied, and they submit a search, automatically apply the track filter and log the results that would show for looking up songs.
- [x] When users have nothing in the search input, clicking through the different tabs shouldn't do anything.
- [x] When there is a text in the search input, clicking through the different tabs should send a new fetch tailored what filter is currently being applied.
- [x] Show a list of search results for all three search filters
- [x] Add all necessary styling to components.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
