### ISSUE TITLE
Feature: User can save song to their library

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to save a song to their library.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Add an option button to tracks that allow users to save them to their library.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 18 10 PM](https://user-images.githubusercontent.com/105886708/200427395-c7fef513-5daf-46f1-83dc-417ab2b80200.png)

![Screen Shot 2022-11-07 at 2 20 24 PM](https://user-images.githubusercontent.com/105886708/200427730-df91a568-d16b-431f-bd6f-8278d08ea6d3.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Ensure that the database is functioning/updating as intended.

### ☁️ Server Tasks

- [x] Create an authorizationMiddleware that verifies that a token exists and allows create valid user payload.
- [x] When user adds a song to their library, send a POST request to the database to save the song and its information.

### ⚡ Client Tasks

- [x] Add an option button to each song in the search result lists that drops down a menu.
- [x] Include an option for users to add song to their library
- [x] Click the add song to library should call a fetch that sends the song and song information to the database.
- [x] Add a modal that disappears after 2 seconds that shows the user that they added the song successfully.
- [x] Fix media queries for all displays.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
