### ISSUE TITLE
Feature: User can delete a song from their library

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to remove a saved song from their library.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Add an option button to saved tracks that allows users to remove them from their library.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 22 48 PM](https://user-images.githubusercontent.com/105886708/200428178-71a8d73f-eaa1-4196-bab3-0788fa216b02.png)

![Screen Shot 2022-11-07 at 2 23 17 PM](https://user-images.githubusercontent.com/105886708/200428196-02a32d45-830f-454a-9afe-536521a17fd1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Make sure database is properly updating/functioning as intended.

### ☁️ Server Tasks

- [x] When users delete a song from their library, send a POST request to the database that removes the song and its information.

### ⚡ Client Tasks

- [x] Add a delete option to the drop down menu of each song in the library.
- [x] Create a modal that asks the user whether they want to confirm the delete or cancel.
- [x] Clicking the delete song button should call a fetch that removes song from library.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
