### ISSUE TITLE
Feature: User can view list of saved songs

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view categories of the songs they have saved in their library.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a home display where users can click into the catalog of their saved songs based on the category they wish to view. Users will also be taken to a separate album view if they click on a specific album.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 28 17 PM](https://user-images.githubusercontent.com/105886708/200429387-cf92799a-72b9-4472-94e5-740bba8ea29e.png)

![Screen Shot 2022-11-07 at 2 29 35 PM](https://user-images.githubusercontent.com/105886708/200429403-b71f4c1e-7afe-4c2f-a983-c63f1fad57ff.png)

![Screen Shot 2022-11-07 at 2 29 55 PM](https://user-images.githubusercontent.com/105886708/200429418-bf5e1b7b-037d-414a-8761-e5be3043be84.png)

![Screen Shot 2022-11-07 at 2 30 10 PM](https://user-images.githubusercontent.com/105886708/200429428-d7868e99-d304-40ac-8ef2-3470dc9a21d5.png)

![Screen Shot 2022-11-07 at 2 30 22 PM](https://user-images.githubusercontent.com/105886708/200429439-40ca145d-febf-476f-b53b-7181c2fe5ab0.png)

![Screen Shot 2022-11-07 at 2 30 31 PM](https://user-images.githubusercontent.com/105886708/200429448-e354bf1f-59b3-4dcd-89a4-8afb72c72699.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Make sure the database is functioning/updating as intended.

### ☁️ Server Tasks

- [x] Create a route that grabs all songs saved to a userId.

### ⚡ Client Tasks

- [x] Add necessary elements to the home page (e.g. headers, tab to view list of songs)
- [x] Clicking the songs tab will take the user to another page and display a list of their saved songs.
- [x] Add an anchor tag that takes the use back to the home screen
- [x] Add all necessary styling.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
