### ISSUE TITLE
Feature: User can create playlist

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to create a playlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a "new playlist" button that users can click to create a new playlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 34 01 PM](https://user-images.githubusercontent.com/105886708/200429799-4f1b427f-4d43-4ec0-a1ff-c49a8395347d.png)

![Screen Shot 2022-11-07 at 2 34 15 PM](https://user-images.githubusercontent.com/105886708/200429817-a9780f9d-06fe-4455-9722-078ab0bb449d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update the data schema so that it includes a playlist table that holds a user playlist user.
- [x] Make sure the database is functioning/updating as intended.

### ☁️ Server Tasks

- [x] Create a POST route that creates playlist and adds to to the database based on userId:
  - [x] Table should include userId, playlistId, and playlist name.

### ⚡ Client Tasks

- [x] Create a playlist tab that takes users to the playlist page.
- [x] The playlist page should have a create new playlist button and a list of the user's playlist if they already have some.
- [x] This should present the user with a modal where they can enter the playlist name and save.
- [x] Add a handleClick function that either closes the modal or adds the new playlist to the database.
- [x] Add a fetch that calls the api and sends the playlist info to the database.
- [x] Style all components.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
