### ISSUE TITLE
Feature: User can add a song to a playlist

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add songs to a playlist by going into the album they wish to add songs to and pressing the "add music" button. Or they can search up a song and click to option button and click "add to playlist". This automatically save the song to their library first before adding it to their desired playlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a button in the playlist view that lets users select songs from their library to add to the desired playlist. Add an option to the option button on tracks that lets users directly add songs to a selected playlist. This automatically adds the song to the users library before adding to a playlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 41 07 PM](https://user-images.githubusercontent.com/105886708/200430921-7b318106-93ee-444b-aa33-abb11970167c.png)

![Screen Shot 2022-11-07 at 2 41 21 PM](https://user-images.githubusercontent.com/105886708/200430936-a7bc9e50-8f8e-4fff-9547-972bbe9ad47c.png)

![Screen Shot 2022-11-07 at 2 41 40 PM](https://user-images.githubusercontent.com/105886708/200430955-a4282264-bb52-44bc-9098-d501b254d014.png)

![Screen Shot 2022-11-07 at 2 41 51 PM](https://user-images.githubusercontent.com/105886708/200430974-43cb8b06-a0f7-48e2-8491-018e42ed1a84.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Add a table that stores songs that are in user playlists:
  - [x] Included columns: playlistId and songId.
- [ ] Make sure database is functioning/updating as intended.

### ☁️ Server Tasks

- [x] Create a POST route that sends songs to a database by playlistId.

### ⚡ Client Tasks

- [ ] Add a handleClick function on the playlists that renders new components:
  - [ ] Album image placeholder.
  - [ ] Name of Album.
  - [ ] Name of current user.
  - [ ] Add music button.
- [ ] The add music button with render a list of all the songs saved in a user's library:
  - [ ] Clicking on the song should add it to the playlist.
- [ ] When users go to view their songs list, add an option to add to playlist:
  - [ ] Pop a modal that lets user choose an album to add to.
- [ ] When users search up a song an an option to add to playlist directly from the discover page:
  - [ ] Include an option to create new playlist with creates a playlist and automatically adds that song to it.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
