### ISSUE TITLE
Feature: User can delete a song from their playlist

### ISSUE THREAD

**Issue by MattKweon** [MattKweon/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to remove a song from their playlists.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Add an option button to the tracks in a playlist that users can click to remove a song from that playlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 44 45 PM](https://user-images.githubusercontent.com/105886708/200431323-f1d118f5-7938-46de-b7ba-cf1a94250100.png)

![Screen Shot 2022-11-07 at 2 45 01 PM](https://user-images.githubusercontent.com/105886708/200431337-f4cb8c96-1c09-4be1-b234-e94dd8f148b5.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Make sure database is properly updating/functioning as intended.

### ☁️ Server Tasks

- [x] When users delete a song from their playlist, send a POST request to the database that removes the song and its information.

### ⚡ Client Tasks

- [x] Add a delete option to the drop down menu of each song in the playlists.
- [x] Create a modal that asks the user whether they want to confirm the delete or cancel.
- [x] Clicking the delete song button should call a fetch that removes song from playlists.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
